package Forms;

import Entities.LoaiPhong;
import Entities.Phong;
import Entities.Tang;
import Entities.ThongTinPhong;
import Entities.TrangThai;
import Models.LoaiPhongDAO;
import Models.PhongDAO;
import Models.TangDAO;
import Models.TrangThaiDAO;
import Utils.CreateRoomStatusMap;
import Utils.mgsBox;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class FormQLTTPhong extends javax.swing.JFrame {

    PhongDAO phongDao;
    LoaiPhongDAO loaiPhongDao;
    TrangThaiDAO trangThaiDAO;
    ThongTinPhong thongTinChiTiet;

    public FormQLTTPhong() {
        initComponents();
        setTitle("Thông tin chi tiết phòng");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        chkSuaDoi = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtSoGiuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUpdate.setText("Sửa Thông tin phòng");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa Phòng");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Số Phòng");

        txtSoPhong.setEditable(false);
        txtSoPhong.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thông tin chi tiết");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Tầng");

        txtTang.setEditable(false);
        txtTang.setEnabled(false);

        jLabel3.setText("Loại phòng");

        jLabel4.setText("Giá Phòng/ giờ");

        txtGiaPhong.setEnabled(false);

        cboLoaiPhong.setEditable(true);
        cboLoaiPhong.setEnabled(false);
        cboLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiPhongItemStateChanged(evt);
            }
        });

        jLabel6.setText("Trạng thái");

        cboTrangThai.setEditable(true);
        cboTrangThai.setEnabled(false);

        chkSuaDoi.setText(" muốn sửa đổi");
        chkSuaDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSuaDoiActionPerformed(evt);
            }
        });

        jLabel7.setText("Số giường");

        txtSoGiuong.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(cboLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtTang))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSuaDoi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cboLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkSuaDoi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSuaDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSuaDoiActionPerformed
        // TODO add your handling code here:
        UpdateStatus();
    }//GEN-LAST:event_chkSuaDoiActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cboLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiPhongItemStateChanged
        // TODO add your handling code here:
        int index = cboLoaiPhong.getSelectedIndex() + 1;

//        System.out.println(String.valueOf(loaiPhongDao.selectById().getSoGiuong()));
//        System.out.println(String.valueOf(loaiPhongDao.selectById().getGiaPhong()));
        txtSoGiuong.setText(String.valueOf(loaiPhongDao.selectById(index).getSoGiuong()));
        txtGiaPhong.setText(String.valueOf(loaiPhongDao.selectById(index).getGiaPhong()));
    }//GEN-LAST:event_cboLoaiPhongItemStateChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void init() {
        phongDao = new PhongDAO();
        loaiPhongDao = new LoaiPhongDAO();
        trangThaiDAO = new TrangThaiDAO();
        thongTinChiTiet = phongDao.selectDetailById(ManHinhQuanLyPhong.posPhong, ManHinhQuanLyPhong.posTang);
        fillComboboxLoaiPhong();
        fillComboboxTrangThai();
        select();
    }

    public void select() {
        txtSoPhong.setText(String.valueOf(thongTinChiTiet.getMaPhong()));
        txtTang.setText(String.valueOf(thongTinChiTiet.getSoTang()));
        cboLoaiPhong.setSelectedIndex(thongTinChiTiet.getMaLP() - 1);
        cboTrangThai.setSelectedIndex(thongTinChiTiet.getMaTT() - 1);
    }

    public void fillComboboxLoaiPhong() {
        List<LoaiPhong> lsLoaiPhong = loaiPhongDao.selectAll();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiPhong.getModel();
        for (LoaiPhong loaiPhong : lsLoaiPhong) {
            model.addElement(loaiPhong.getTenLP());
        }
    }

    public void fillComboboxTrangThai() {
        List<TrangThai> lsTT = trangThaiDAO.selectAll();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTrangThai.getModel();
        for (TrangThai trangThai : lsTT) {
            model.addElement(trangThai.getTenTrangThai());
        }
    }

    public void update() {
        if (ischeckNum(txtGiaPhong.getText().trim())) {
            if (Integer.parseInt(txtSoGiuong.getText()) > 0) {
                try {
                    phongDao.update(new Phong(Integer.parseInt(txtSoPhong.getText()), Integer.parseInt(txtTang.getText()), cboLoaiPhong.getSelectedIndex() + 1, cboTrangThai.getSelectedIndex() + 1, null));
                    updateStatusScreen();
                    mgsBox.alert(FormQLTTPhong.this, "Cập nhật thành công");
                    this.setVisible(false);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                mgsBox.alert(FormQLTTPhong.this, "So giuong khong hop le");
            }
        } else {
            mgsBox.alert(FormQLTTPhong.this, "Gia phong khong hop le");
        }
    }

    public void delete() {
        if (mgsBox.confirm(FormQLTTPhong.this, "Bạn có chắc muốn xóa phòng " + ManHinhQuanLyPhong.posPhong + " không ?")) {
            phongDao.deletePhong(ManHinhQuanLyPhong.posTang, ManHinhQuanLyPhong.posPhong);
            mgsBox.alert(FormQLTTPhong.this, "Delete thành công");
            this.setVisible(false);
            updateStatusScreen();
        }
    }

    public void updateStatusScreen() {
        ManHinhQuanLyPhong.jpnAreaRoomMap.removeAll();
        ManHinhQuanLyPhong.setBox();
        List<Integer> ls = phongDao.RoomPerFloor();
        for (int i = 0; i < ls.size(); i++) {
            CreateRoomStatusMap.createMapRoom(ManHinhQuanLyPhong.jpnAreaRoomMap, ManHinhQuanLyPhong.gbc, i, ls.get(i));
            ManHinhQuanLyPhong.jpnAreaRoomMap.revalidate();
        }
    }

    public void UpdateStatus() {
        if (chkSuaDoi.isSelected()) {
            cboLoaiPhong.setEnabled(true);
            cboTrangThai.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            txtGiaPhong.setEnabled(false);
            txtSoGiuong.setEnabled(false);
            cboLoaiPhong.setEnabled(false);
            cboTrangThai.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    public boolean ischeckNum(String txt) {
        try {
            double n = Double.parseDouble(txt);
            if (n <= 0) {
                return false;
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JCheckBox chkSuaDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtSoGiuong;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTang;
    // End of variables declaration//GEN-END:variables
}
