/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entities.Phong;
import Models.PhongDAO;
import Models.TangDAO;
import Utils.CreateRoomStatusMap;
import Utils.RoomMapToDisplay;
import Utils.XImage;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author you have to better
 */
public class ManHinhQuanLyPhong extends javax.swing.JFrame {

    public static int posTang;
    public static int posPhong;
    public static int soTang;
    public static int soPhong;
    public static int soPhongBD;
    public static int widthContainer;
    public static int heightContainer;
    public static List<Phong> lsPhong;
    public static List<JButton[]> lsJbutton;
    PhongDAO dao;
    TangDAO tangDao;
    public static GridBagConstraints gbc;

    public ManHinhQuanLyPhong() {
        initComponents();
        setTitle("Quan ly phong khach san");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addWindowListener(new closeYourWindows());
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspMapRoom = new javax.swing.JScrollPane();
        jpnAreaRoomMap = new javax.swing.JPanel();
        btnQuickCreate = new javax.swing.JButton();
        blbFloorNum = new javax.swing.JLabel();
        sldSize = new javax.swing.JSlider();
        lblSize = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnAreaRoomMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jpnAreaRoomMap.setLayout(new javax.swing.BoxLayout(jpnAreaRoomMap, javax.swing.BoxLayout.Y_AXIS));
        jspMapRoom.setViewportView(jpnAreaRoomMap);

        btnQuickCreate.setText("Tạo sơ đồ phòng nhanh");
        btnQuickCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickCreateActionPerformed(evt);
            }
        });

        blbFloorNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blbFloorNum.setText("Số Tầng");
        blbFloorNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255)));

        sldSize.setMaximum(150);
        sldSize.setMinimum(50);
        sldSize.setMinorTickSpacing(1);
        sldSize.setPaintLabels(true);
        sldSize.setPaintTicks(true);
        sldSize.setValue(100);
        sldSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSizeStateChanged(evt);
            }
        });

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSize.setText("100");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blbFloorNum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuickCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspMapRoom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sldSize, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blbFloorNum, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(btnQuickCreate)
                    .addComponent(btnLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspMapRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sldSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuickCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickCreateActionPerformed
        // TODO add your handling code here:
        FormTaoMapNhanh f = new FormTaoMapNhanh();
        f.setVisible(true);
    }//GEN-LAST:event_btnQuickCreateActionPerformed

    private void sldSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSizeStateChanged
        // TODO add your handling code here:
        widthContainer = sldSize.getValue();
        heightContainer = sldSize.getValue();
        lblSize.setText(widthContainer + " %");
        jpnAreaRoomMap.removeAll();
        jpnAreaRoomMap.repaint();
        FillRoomToScreen();
    }//GEN-LAST:event_sldSizeStateChanged

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        jpnAreaRoomMap.removeAll();
        FillRoomToScreen();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    public void init() {
        posTang = 0;
        posPhong = 0;
        soPhong = 0;
        soTang = 0;
        widthContainer = 100;
        heightContainer = 100;
        soPhongBD = 0;
        lsPhong = new ArrayList<>();
        lsJbutton = new ArrayList<>();
        gbc = new GridBagConstraints();
        dao = new PhongDAO();
        tangDao = new TangDAO();
        FillRoomToScreen();
    }
    
    // tao so do phong voi co so du lieu san co vao jpanel jpnAreaRoomMap
    public void FillRoomToScreen() {
        setBox();
        List<Integer> ls = dao.RoomPerFloor();
        if (ls != null) {
            for (int i = 0; i < ls.size(); i++) {
                CreateRoomStatusMap.createMapRoom(jpnAreaRoomMap, gbc, i, ls.get(i));
                jpnAreaRoomMap.revalidate();
            }
        }
    }
    
    // setlayout cho jpnAreaRoomMap
    public static void setBox() {
        jpnAreaRoomMap.setLayout(new GridBagLayout());
        gbc.fill = GridBagConstraints.NONE;
        gbc.weightx = 1;
        gbc.weighty = 1;
    }

    public class closeYourWindows extends WindowAdapter{

        @Override
        public void windowClosed(WindowEvent we) {
            RoomMapToDisplay.updateStatusScreen();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbFloorNum;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQuickCreate;
    public static javax.swing.JPanel jpnAreaRoomMap;
    private javax.swing.JScrollPane jspMapRoom;
    private javax.swing.JLabel lblSize;
    private javax.swing.JSlider sldSize;
    // End of variables declaration//GEN-END:variables
}
