/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entities.Phong;
import Models.PhongDAO;
import Models.TangDAO;
import Utils.CreateRoomStatusMap;
import Utils.XImage;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author you have to better
 */
public class ManHinhQuanLyPhong extends javax.swing.JFrame {

    public static int posTang;
    public static int posPhong;
    public static int soTang;
    public static int soPhong;
    public static int soPhongBD;
    public static int widthContainer;
    public static int heightContainer;
    public static List<Phong> lsPhong;
    public static List<JButton[]> lsJbutton;
    PhongDAO dao;
    TangDAO tangDao;
    GridBagConstraints gbc;

    public ManHinhQuanLyPhong() {
        initComponents();
        setTitle("Quan ly phong khach san");
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspMapRoom = new javax.swing.JScrollPane();
        jpnAreaRoomMap = new javax.swing.JPanel();
        btnQuickCreate = new javax.swing.JButton();
        btnTaoTang = new javax.swing.JButton();
        blbFloorNum = new javax.swing.JLabel();
        sldSize = new javax.swing.JSlider();
        lblSize = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnAreaRoomMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jpnAreaRoomMap.setLayout(new javax.swing.BoxLayout(jpnAreaRoomMap, javax.swing.BoxLayout.Y_AXIS));
        jspMapRoom.setViewportView(jpnAreaRoomMap);

        btnQuickCreate.setText("Tạo sơ đồ phòng nhanh");
        btnQuickCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickCreateActionPerformed(evt);
            }
        });

        btnTaoTang.setText("Thêm Tầng");
        btnTaoTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTangActionPerformed(evt);
            }
        });

        blbFloorNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blbFloorNum.setText("Số Tầng");
        blbFloorNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255)));

        sldSize.setMaximum(150);
        sldSize.setMinimum(50);
        sldSize.setMinorTickSpacing(1);
        sldSize.setPaintLabels(true);
        sldSize.setPaintTicks(true);
        sldSize.setValue(100);
        sldSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSizeStateChanged(evt);
            }
        });

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSize.setText("100");

        btnReset.setText("Tạo lại toàn bộ phòng");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQuickCreate)
                        .addGap(37, 37, 37)
                        .addComponent(btnTaoTang, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(953, 953, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blbFloorNum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jspMapRoom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sldSize, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickCreate)
                    .addComponent(btnTaoTang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blbFloorNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspMapRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnReset))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuickCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickCreateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnQuickCreateActionPerformed

    private void btnTaoTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTaoTangActionPerformed

    private void sldSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSizeStateChanged
        // TODO add your handling code here:
//        widthContainer = sldSize.getValue();
//        lblSize.setText(widthContainer + " %");
//        jpnAreaRoomMap.removeAll();
//        FillRoomToScreen();
//        CreateRoomStatusMap.createMapRoom(jpnAreaRoomMap,gbc, soTang, soPhong);
    }//GEN-LAST:event_sldSizeStateChanged

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    public void init() {
        posTang = 0;
        posPhong=0;
        soPhong = 0;
        soTang = 0;
        widthContainer = 100;
        heightContainer = 100;
        soPhongBD = 0;
        lsPhong = new ArrayList<>();
        lsJbutton = new ArrayList<>();
        gbc = new GridBagConstraints();
        dao = new PhongDAO();
        tangDao = new TangDAO();
        FillRoomToScreen();
    }

    public void insert() {
    }

    public void update() {
    }

    public void delete() {
    }

    public void select() {
        lsPhong = dao.selectAll();
        soTang = tangDao.selectAll().size();

    }

    // tao so do phong voi co so du lieu san co vao jpanel jpnAreaRoomMap
    public void FillRoomToScreen() {

        setBox();
        List<Integer> ls = dao.RoomPerFloor();
        for (int i = 0; i < ls.size(); i++) {
            CreateRoomStatusMap.createMapRoom(jpnAreaRoomMap, gbc, i, ls.get(i));
            jpnAreaRoomMap.revalidate();
        }
    }

    // setlayout cho jpnAreaRoomMap
    public void setBox() {
        jpnAreaRoomMap.setLayout(new GridBagLayout());
        gbc.fill = GridBagConstraints.NONE;
        gbc.weightx = 1;
        gbc.weighty = 1;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhQuanLyPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbFloorNum;
    private javax.swing.JButton btnQuickCreate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTaoTang;
    private javax.swing.JPanel jpnAreaRoomMap;
    private javax.swing.JScrollPane jspMapRoom;
    private javax.swing.JLabel lblSize;
    private javax.swing.JSlider sldSize;
    // End of variables declaration//GEN-END:variables
}
